zuul:
  ignoredServices: '*'
  routes:
    products:
      retryable: true
      stripPrefix: false
      path: /api/products/**
      serviceId: products
products:
  ribbon:
    listOfServers: http://localhost:8081, http://localhost:8082
    retryableStatusCodes: 404, 500
    NFLoadBalancerRuleClassName: com.example.gateway.CustomRule


ribbon:
  MaxAutoRetries: 2
  MaxAutoRetriesNextServer: 3
  OkToRetryOnAllOperations: true
  ConnectTimeout: 2000
  ReadTimeout: 2000

hystrix:
  command:
    products:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000